default_platform(:android)

platform :android do
  desc "Build and upload production release"
  lane :release do
    gradle(task: "bundle", build_type: "Release")
    upload_to_play_store(
      track: "production",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true
    )
  end
end

platform :ios do
  desc "Build and upload production release"
  lane :release do
    build_ios_app(scheme: "Runner", export_method: "app-store")
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      skip_app_version_update: true
    )
  end
end
